### ISSUE TITLE
Admin page

### ISSUE THREAD

**Issue by alexschedrov** [drupal-ukraine/advanced_forum#11]
Let's create empty admin page(without form for settings).
See `advanced_forum_settings_page()`.

Some examples:
_/advanced_forum.routing.yml_

``` yaml
advanced_forum.admin_settings:
  path: '/admin/config/content/advanced-forum'
  defaults:
    _form: '\Drupal\advanced_forum\Form\SettingsForm'
    _title: 'Advanced Forum settings'
  requirements:
    _permission: 'administer advanced forum'
```

_/src/Form/SettingsForm.php_

``` php
<?php

/**
 * @file
 * Contains \Drupal\advanced_forum\Form\SettingsForm.
 */

namespace Drupal\advanced_forum\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

/**
 * Defines a form that configures advanced forum settings.
 */
class SettingsForm extends ConfigFormBase {

  /**
   * {@inheritdoc}
   */
  public function getFormId() {
    return 'advenced_forum_admin_settings_form';
  }

  /**
   * {@inheritdoc}
   */
  protected function getEditableConfigNames() {
    return [
      'advanced_forum.settings',
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state, Request $request = NULL) {
    // @todo implement settings form.
    return parent::buildForm($form, $form_state);
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    // @todo implement submit handler.
  }
}

```

Related to https://www.drupal.org/node/2291273
